INSERT INTO CUSTOMER(ADDRESS, CELL_PHONE, CITY, EMAIL, HOME_PHONE, NAME, POSTAL, PROVINCE)
 VALUES ('123 playground street', '416-857-0231','Brampton','vuongv@sheridancollege.ca','123-456-1234','Henry','L6S5H7','Ontario');
 
 INSERT INTO WORK_ORDER(WORK_ORDER_ID, ORDER_DATE, ORDER_COST, APPOINTMENT_DATE, APPOINTMENT_TIME, WORKER, SERVICE) 
VALUES (1,'2020-12-20',1000,'2021-04-01','10:00:00', 'Kap3', 'Chimney cleaning'),(2,'2020-12-20',1000,'2021-04-01','10:00:00', 'Kap2', 'Chimney Installation') ;

 

INSERT INTO CUSTOMER_WORK_ORDERS(CUSTOMER_ID,WORK_ORDERS_WORK_ORDER_ID) 
VALUES(1,1),(1,2);

INSERT INTO WORK_WORKER(NAME) VALUES ('Kap3');
INSERT INTO WORK_WORKER(NAME) VALUES ('Kap2');
INSERT INTO WORK_WORKER(NAME) VALUES ('Henry');
INSERT INTO WORK_WORKER(NAME) VALUES ('Amazon');
INSERT INTO WORK_WORKER(NAME) VALUES ('Zesus');

INSERT INTO WORK_SERVICE(SERVICE_COST,SERVICE_DESCRIPTION, SERVICE_DURATION, SERVICE_NAME) 
VALUES (50,'Chimney cleaning',1,'Chimney cleaning');
INSERT INTO WORK_SERVICE(SERVICE_COST,SERVICE_DESCRIPTION, SERVICE_DURATION, SERVICE_NAME) 
VALUES (2000,'Chimney Installation',4,'Chimney Installation');

INSERT INTO User (email, encrypted_Password, enabled) VALUES
('simon.hood@sheridancollege.ca', '$2a$10$1ltibqiyyBJMJQ4hqM7f0OusP6np/IHshkYc4TjedwHnwwNChQZCy', 1),
('jonathan.penava@sheridancollege.ca', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

INSERT INTO Role (rolename) VALUES ('ROLE_USER'),
('ROLE_GUEST');
INSERT INTO User_Roles VALUES (1, 1),
(1, 2), (2, 2);

INSERT INTO Testimonial (SERVICE_NAME, USER_EMAIL, USER_NAME, USER_TESTIMONIAL, TO_DISPLAY) VALUES ('Chimney Installation', 'seby_97@yahoo.ca', 'Sebastian Koehler','i love cookies and fireplaces!', TRUE);
INSERT INTO Testimonial (SERVICE_NAME, USER_EMAIL, USER_NAME, USER_TESTIMONIAL, TO_DISPLAY) VALUES ('Chimney cleaning', 'TEST_97@yahoo.ca', 'TEST Koehler','I LOVE FIREPLACES!', FALSE);