INSERT INTO CUSTOMER(ADDRESS, CELL_PHONE, CITY, EMAIL, HOME_PHONE, NAME, POSTAL, PROVINCE)
 VALUES ('123 playground street', '416-857-0231','Brampton','vuongv@sheridancollege.ca','123-456-1234','Henry','L6S5H7','Ontario');
 
 INSERT INTO WORK_ORDER(WORK_ORDER_ID, ORDER_DATE, ORDER_COST, APPOINTMENT_DATE, APPOINTMENT_TIME) 
VALUES (1,'2020-12-20',1000,'2021-04-01','10:00:00');

INSERT INTO CUSTOMER_WORK_ORDERS(CUSTOMER_ID,WORK_ORDERS_WORK_ORDER_ID) 
VALUES(1,1);

INSERT INTO WORK_WORKER(NAME) VALUES ('Kap3');

INSERT INTO WORK_WORKER_ORDER_LIST (WORK_WORKER_ID, ORDER_LIST_WORK_ORDER_ID) VALUES (1,1);

INSERT INTO WORK_SERVICE(SERVICE_COST,SERVICE_DESCRIPTION, SERVICE_DURATION, SERVICE_NAME) 
VALUES (50,'Chimney cleaning',1,'Chimney cleaning');

INSERT INTO WORK_SERVICE_ORDER_LIST (WORK_SERVICE_SERVICE_ID,ORDER_LIST_WORK_ORDER_ID) 
values (1,1);